return {
	"folke/snacks.nvim",
	priority = 1000,
	lazy = false,
	---@type snacks.Config
	opts = {
		bigfile = { enable = true },
		dashboard = {
			enable = true,
			sections = {
				{ section = "header" },
				{ section = "keys", padding = 1 },
				{ section = "recent_files", title = "Recent files", padding = 1 },
				{ section = "startup" },
			},
		},
		explorer = { enable = true },
		indent = { enable = true },
		input = { enable = true },
		notifier = { enable = true },
		picker = { enable = true },
		quickfile = { enable = true },
		scope = { enable = true },
		scroll = { enable = true },
		statuscolumn = { enable = true },
		words = { enable = true },
		-- animate ={enable = false},
		-- bufdelete ={enable = false},
		-- debug ={enable = false},
		-- dim ={enable = false},
		-- git ={enable = false},
		-- gitbrowse ={enable = false},
		-- image ={enable = false},
		-- layout ={enable = false},
		-- lazygit ={enable = false},
		-- notify ={enable = false},
		-- profiler ={enable = false},
		-- rename ={enable = false},
		-- scratch ={enable = false},
		-- terminal ={enable = false},
		-- toggle ={enable = false},
		-- util ={enable = false},
		-- win ={enable = false},
		-- zen ={enable = false},
	},
    keys = {
        { "<leader>e", function() Snacks.explorer() end, desc = "File Explorer" },
    }
}
