return {
	-- "zbirenbaum/copilot.lua",
	-- cmd = "Copilot",
	-- build = ":Copilot auth",
	-- event = "BufReadPost",
	-- opts = {
	-- 	panel = { enabled = false },
	-- 	suggestion = { enabled = true, auto_trigger = true },
	-- },
	-- config = function(_, opts)
	-- 	require("copilot").setup(opts)
	--
	-- 	vim.api.nvim_create_autocmd("User", {
	-- 		pattern = "BlinkCmpMenuOpen",
	-- 		callback = function()
	-- 			vim.b.copilot_suggestion_hidden = true
	-- 		end,
	-- 	})
	--
	-- 	vim.api.nvim_create_autocmd("User", {
	-- 		pattern = "BlinkCmpMenuClose",
	-- 		callback = function()
	-- 			vim.b.copilot_suggestion_hidden = false
	-- 		end,
	-- 	})
	-- end,
	-- keys = {
	-- 	{
	-- 		"<leader>cp",
	-- 		function()
	-- 			vim.cmd("Copilot panel")
	-- 		end,
	-- 		{ desc = "Toggle Copilot Panel" },
	-- 	},
	-- },
}
